### ISSUE TITLE
Trouble using couch-docs to dump design docs

### ISSUE THREAD

**Issue by grempe** [eee-c/couch_docs#1]
Hi,

I am testing out couch-docs, and want to try to dump the design and standard docs from a DB with about 90mm records in it.

I first tried to dump just the design docs and hit a brick wall.

```
root:/tmp/couch_dump# couch-docs dump -d "http://localhost:5984/searchlight_production"
/usr/local/lib/ruby/gems/1.8/gems/json-1.2.3/lib/json/common.rb:128:in `initialize': can't convert RestClient::Response into String (TypeError)
    from /usr/local/lib/ruby/gems/1.8/gems/json-1.2.3/lib/json/common.rb:128:in `new'
    from /usr/local/lib/ruby/gems/1.8/gems/json-1.2.3/lib/json/common.rb:128:in `parse'
    from /usr/local/lib/ruby/gems/1.8/gems/couch_docs-1.1.0/lib/couch_docs/store.rb:62:in `get'
    from /usr/local/lib/ruby/gems/1.8/gems/couch_docs-1.1.0/lib/couch_docs/store.rb:68:in `each'
    from /usr/local/lib/ruby/gems/1.8/gems/couch_docs-1.1.0/lib/couch_docs.rb:63:in `map'
    from /usr/local/lib/ruby/gems/1.8/gems/couch_docs-1.1.0/lib/couch_docs.rb:63:in `dump'
    from /usr/local/lib/ruby/gems/1.8/gems/couch_docs-1.1.0/lib/couch_docs/command_line.rb:23:in `run'
    from /usr/local/lib/ruby/gems/1.8/gems/couch_docs-1.1.0/lib/couch_docs/command_line.rb:11:in `run'
    from /usr/local/lib/ruby/gems/1.8/gems/couch_docs-1.1.0/bin/couch-docs:10
    from /usr/local/bin/couch-docs:19:in `load'
    from /usr/local/bin/couch-docs:19
```

Here is my Ruby info (Running Ruby Enterprise Edition):

```
root:/tmp/couch_dump# ruby -v
ruby 1.8.7 (2009-06-12 patchlevel 174) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 20090928
```

And here is a link to the gems installed and my 'gem env' if thats helpful.

http://pastie.org/871132

If I run dump with '-D' to dump all docs, it does nothing visible.  But I killed it before it had a chance perhaps to really do any work on such a large DB?

Thoughts?  Thank you.

**Comment by jo** [comment]
just to mention:

RestClient has changed the response API. Its now a Ruby Object and one needs to call _body_ on it in order to retrieve the string.

Greetings
Johannes

**Comment by eee-c** [comment]
Yah, I coded against RestClient 1.1. I'll push out a 1.1.1 that works with RestClient 1.4 tonight.  Thanks for the pointer Johannes.

I do not have much faith in dumping 90 million documents.  It works fine for thousands of docs (which is what I use it for), but I would guess that millions of docs would prove fruitless.

**Comment by grempe** [comment]
Thanks for the quick response.  I'll try it out tonight when you release.  If you could send me a ping when its done that would be great.

Regarding dumping large numbers of docs.  Does the dump process put individual json files for each document in the same dir?  Or in a hierarchy of dirs?  If it were a hierarchy, or a single large file that you concatenate to, it might have some chance of success.

**Comment by eee-c** [comment]
couch_docs 1.1.1 should resolve this issue. Rather than update the code to work with RestClient 1.4, I locked the gem requirements to RestClient 1.1.
