### ISSUE TITLE
Support for JSON in Design Docs

### ISSUE THREAD

**Issue by dacc** [eee-c/couch_docs#6]
Some design doc keys have more complex JSON values than simply a string of Javascript for e.g. map / reduce functions.  For example, it's nice to have couch_docs manage keeping your rewrite definitions up-to-date, which are defined in an array.

So e.g. it would be nice to have (on the filesystem):

db/_design/myapp/rewrites.json

.. and get a design doc like:

<pre>
{
  "_id": "_design/myapp",
  "rewrites": [
  {
    "from": "/this",
    "to": "that"
  }
]
}
</pre>

**Comment by dacc** [comment]
I think I have solved this with 9850a54da369c29eb638be677fac1a36f51862f3, but a new ticket should then be created for dumping support.

**Comment by eee-c** [comment]
Included in the 1.3 release (finally).
