### ISSUE TITLE
Implicit Dependency on Bones 2

### ISSUE THREAD

**Issue by dacc** [eee-c/couch_docs#8]
Apparently "Bones.setup" disappeared in v3:

<pre>
{dan@ledog ~/src/couch_docs}$ rake
(in /Users/dan/src/couch_docs)
rake aborted!
undefined method `setup' for Bones:Module
/Users/dan/src/couch_docs/Rakefile:7
(See full trace by running task with --trace)

{dan@ledog ~/src/couch_docs}$ gem list | grep bones
bones (3.4.1)
</pre>

**Comment by dacc** [comment]
Not sure how to submit patches (new to github).  I just forked and committed there -- is that the right way?  And then I reference by giving you the commit "id?"

862ffa3b842562ed7a4c8c493451e9edc91db807

**Comment by eee-c** [comment]
Pull request is what you're looking for: http://github.com/guides/pull-requests

Thanks!

**Comment by eee-c** [comment]
Switch to Jeweler for gem maintenance. Re-org specs to mirror the classes that they describe. closed by c53aa35205b6e0c322a5b893a12c8bc85c05fcd9

**Comment by eee-c** [comment]
Heh.  Sorry to close it out after you worked up a patch. I don't have the brain capacity for multiple gem maintenance packages, so I'm switching to jeweler.
